# UBICACIÓN: backend/catalogos.py

# Lista exacta de tu imagen "Entidad Bancaria"
LISTA_BANCOS = [
    "Banco Agromercantil", "Banco Azteca", "Banco CHN", "Banco Credicorp",
    "Banco Cuscatlan", "BAC", "Banco de Antigua", "Banco de los Trabajadores",
    "Banco Ficohsa", "Banco G&T", "Banco Industrial", "Banco INV",
    "Banco Multimoney", "Banco Nexa", "Banco Promerica", "Banrural",
    "Citibank", "Interbanco", "Vivibanco"
]

# PDF: Códigos de tipos de ciberataques
DICT_ATAQUES = {
    # Tendencia 1: Contenido abusivo
    '1'   : 'Contenido abusivo',
    '11'  : 'Correo marivo no solicitado (SPAM)',
    '1101': 'Contenido malicioso',
    '1102': 'Contenido comercial',
    '1103': 'Mensajes fraudulentos',
    '1104': 'Correo no deseado de mensajería instantánea',
    '1105': 'Correo no deseado de motores de búsqueda',
    '1106': 'Correo no deseado por blogs',
    '1107': 'Correo no deseado de wiki',
    '1108': 'Correo no deseado de foros de internet',
    '1109': 'Correo no deseado de noticias de usenet',  
    # Tendencia 2: Contenido dañino
    '2'   : 'Contenido dañino',
    '21'  : 'Software malicioso (Malware)',
    '2101': 'Ransomware',
    '2102': 'Spyware',
    '2103': 'Adware',
    '2104': 'Crimeware',
    '2105': 'Gusanos',
    '2106': 'Troyanos',
    '2107': 'Botnets',
    '2108': 'Virus',
    '2109': 'Rootkits',
    '2110': 'Mando y control (C&C)',
    '2111': 'Dialer',
    '2112': 'Conexión sospechosa',
    '2113': 'Remote administration tool (RAT)',
    '2114': 'Exploits',
    '2115': 'Advanced persistent threat (APT)',
    '2116': 'Rogueware',
    '2117': 'Keyloggers',
    '2118': 'Puertas traseras (Backdoors)',
    '2119': 'Criptojacking',
    '2120': 'Aplicaciones maliciosas',
    '2121': 'Envenenamiento SEO',
    # Tendencia 3: Obtención de información / Ingeniería Social
    '3'   : 'Obtención de información',
    '31'  : 'Escaneo malicioso',
    '3101': 'Escaneo de puertos',
    '3102': 'Escaneo de red',
    '3103': 'Escaneo de tecnologías',
    '3104': 'Análisis de paquetes del tráfico de red (Sniffing)',
    '3105': 'Eavesdropping',
    '3106': 'IP maliciosas',
    '3107': 'Web malicioso',
    '3108': 'Peticiones de sistema de nombre de dominio (DNS)',
    '3109': 'Peticiones de protocolo de control de mensajes de internet (ICMP)',
    '3110': 'Peticiones de protocolo para transferencia simple de correo (SMTP)',
    '3111': 'Fingerprinting',
    '32'  : 'Ingeniería social',
    '3201': 'Pretexting',
    '3202': 'Dumpster diving',
    '3203': 'Shoulder surfing',
    '3204': 'Baiting',
    '3205': 'Smishing',
    '3206': 'Vishing',
    '3207': 'Sextorsión',
    '3208': 'Mentiras',
    '3209': 'Trucos',
    '3210': 'Sobornos',
    '3211': 'Amenazas',
    '3212': 'Phishing',
    '3213': 'Spoofing',
    '3214': 'Suplantación de identidad',
    '3215': 'Web scraping',
    '3216': 'Estafa',
    '3217': 'Delitos contra la imagen',
    '3218': 'Redes trampa',
    '3219': 'Hombre en el medio (MitM)',
    '3220': 'Robo de información en ficheros de páginas web (Cookies)',
    '3221': 'Spear phishing',
    '3222': 'Whaling',
    # Tendencia 4: Intrusión
    '4'   : 'Intrusión',
    '41'  : 'Inyección de código',
    '4101': 'Inyección de lenguaje de consulta estructurada (SQL)',
    '4102': 'Cross Site Scripting (XSS)',
    '4103': 'Inserción de comandos',
    '4104': 'Ejecución de comandos',
    '4105': 'Concatenación de comandos',
    '42': 'Robo por intrusión',
    '4201': 'Intrusión física',
    '43': 'Intrusión en la seguridad de la capa de transporte (SSL)',
    '4301': 'Poodle',
    '4302': 'Freak',
    '4303': 'Heartbleed',
    '4304': 'Shellshock',
    '4305': 'Bar mitzvah',
    # Tendencia 5: Disponibilidad
    '5'   : ' Compromiso a la disponibilidad',
    '51'  : 'Ataque de denegación de servicio (DOS) y distribuido (DDoS)',
    '5101': 'Inundación de números de secuencia iniciales (SYN)',
    '5102': 'Inundación packet internet network groper (PING)',
    '5103': 'Inundación de aplicación',
    '5104': 'Amplificación utilizando servicios basados protocolos de datagramas de usuario (UDP)',
    '5105': 'Smurf',
    '5106': 'Fragmentación',   
    '5107': 'Peer to peer (P2P)',
    '5108': 'Ataque de denegación de serviciso permanente (PdoS)',
    '5109': 'Zombi pulsante',
    '5110': 'Desbordamiento de memoria',
    '5111': 'Nuke',
    '5112': 'Reflejos',
    '5113': 'Inundaciones involuntarias',
    '5114': 'Ataques de fuerza bruta',
    '5115': 'Ataque de denegación de servicios de telefonía (TDoS)',
    # Tendencia 6 y 7
    '6'   : ' Compromiso de información',
    '61'  : 'Pérdida o robo de datos',
    '6101': 'Pérdida de datos por fallo de componente de tecnología',
    '6102': 'Pérdida de datos por robo físico',
    '62'  : 'Modificación de información no autorizada',
    '6201': 'Modificación empleando credenciales sustraídas de un sistema o aplicación',
    '7'   : 'Fraude',
    '71'  : 'Uso no autorizado de recursos',
    '7101': 'Uso de correo electrónico para participar en estafas piramidales',
    '7102': 'Ingreso no autorizado a los sistemas haciendo uso de privilegios excesivos',
    '72'  : 'Derechos de autor',
    '7201': 'Warez',
    '7202': 'Falsificación',
    '7203': 'Contrabando',
}

# PDF: Códigos de hardware/software detector
DICT_DETECTOR = {
    '1': 'WAF (Web App Firewall)',
    '2': 'Firewall',
    '3': 'Antivirus',
    '4': 'IPS (Prevención Intrusos)',
    '5': 'IDS (Detección Intrusos)',
    '6': 'Antispam',
    '7': 'Antispyware',
    '8': 'Antiphishing',
    '9': 'AntiDDoS',
    '10': 'AntiBot',
    '11': 'Filtrado de contenido WEB',
    '12': 'Gestión de información y eventos de seguridad (SIEM)',
    '13': 'Software de prevención de pérdida de data (DLP)',
    '14': 'Servicios gestionados de detección y respuesta (MDR)',
    '15': 'Sandbox',
    '16': 'Honeypots',
    '17': 'Gestión unificada de amenazas (UTM)',
    '18': 'Servidor proxy',
    '19': 'Usuario del servicio',
    '20': 'Colaborador de la entidad',
    '21': 'Proveedor de Servicios'
}

# PDF: Guía (Criticidad)
DICT_CRITICIDAD = {
    '1': 'Informativo',
    '2': 'Baja',
    '3': 'Media',
    '4': 'Alta',
    '5': 'Crítico'
}

# Códigos de País (Ejemplos comunes ISO)
DICT_PAISES = {
    '320': 'Guatemala',
    '840': 'Estados Unidos',
    '156': 'China',
    '643': 'Rusia',
    '076': 'Brasil',
    '276': 'Alemania',
    '484': 'México',
    '999': 'Desconocido'
}